# Generated by Django 3.2 on 2021-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(help_text='Enter phone number', max_length=12),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.CharField(help_text='Enter phone number', max_length=12),
        ),
    ]
