# Generated by Django 3.2 on 2021-04-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20210422_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='bookapp/static/images'),
        ),
    ]
